version: "3.9"

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  backend:
    image:
      - omnilink-backend
    volumes:
      - ./:app
    depends_on:
      - db
    ports:
      - "3030:8080"
